version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: '12:00'
    timezone: Europe/Helsinki
  open-pull-requests-limit: 10
  reviewers:
  - nikoheikkila
  rebase-strategy: disabled
